## YAML Template.
---
layers:
  -
    #bedrock
    type: 7 
    miny: 0
    maxy: 0
  -
    #dirt
    type: 3
    miny: 1
    maxy: 9    
  -
    #grass
    type: 2
    miny: 10
    maxy: 10
    
grid:
  #grid enabled
  enabled: true
  #height at which the grid should be placed
  height: 11
  #size of the biggest grid, should be power of 2
  defaultSize: 128
  #type of the inside of a grid square
  #in this case, planks
  innertype: 5
  #type of the border of a grid square
  #in this case, stone
  bordertype: 1
  #sizes of other squares
  othersizes:
    -
      #size 64, chance of a 128 tile being split into 4*64 is 50%
      size: 64
      chance: 50
    -
      #size 32, chance of a 64 tile being split into 4*32 is 25%
      size: 32
      chance: 25
  